### ISSUE TITLE
Remove Center from each child

### ISSUE THREAD

**Issue by qaniel** [serenader2014/flutter_carousel_slider#97] opened 2020-01-22 17:54 UTC
The plugin is forcing a center widget in each of its elements, constraining the application of this plugin.

E.g If i want the carousel to have the image at top of the screen it would be almost impossible because of this Center widget without using some obscure hacky stuff ;)

There is some way to don't force this behavior in the carousel?

**Comment by pradt** [comment] 2020-01-26 13:39
I'm getting all siblings being centered - is this what you are experiencing ?

Do you have a work around ?

**Comment by qaniel** [comment] 2020-01-27 04:30
@pradt I couldn't find a workaround, so far I changed to another plugin [flutter_swiper](https://pub.dev/packages/flutter_swiper) due to the short time, it looks like it's getting only bug fixes but saved me in this case. Maybe you can fork this and implement a solution?

**Comment by jacksonw765** [comment] 2020-03-22 15:41
I would really like this as well

**Comment by serenader2014** [comment] 2020-04-13 13:17
Hi, sorry for the late response.

Yes, currently the carousel item is wrapped in a `Center` widget. Maybe we can add an option to disable the center widget in next release.

**Comment by Vasantika20** [comment] 2020-05-29 05:03
Is there any update to set widget at left not in center only?

**Comment by KazokuAkio** [comment] 2020-06-18 04:01
up vote for this, i need it also, when i disabled infinite scroll, the first child have space on left side.

**Comment by serenader2014** [comment] 2020-06-21 16:07
Hi all, just want to let you know that I have released a new version, and provide a way to disable the Center widget, please upgrade to v2.2.0 and give it a try.

I'm closing this issue, but if you have any further issues, feel free to reopen it.

**Closed by serenader2014** 2020-06-21 16:07 UTC

**Comment by rivetingpeppermint** [comment] 2020-06-23 08:08
I copy-pasted the example code, tried it using v2.2.0 but the widget is still centered like this picture below. Is there any way to make it start on the left?<br>![Image of screenshot](https://i.imgur.com/dJgpWSP.png)

**Comment by serenader2014** [comment] 2020-06-23 15:44
Hi @rivetingpeppermint , you can set the `viewportFraction` to `1`, that will make the carousel item occupy the whole page.

**Comment by rivetingpeppermint** [comment] 2020-06-24 00:41
The problem is I wanted something like this picture below (the one on the left), where the next carousel item peeks on the right. How can I achieve this?<br>
![screenshot](https://cdn.dribbble.com/users/1757119/screenshots/5185063/post_for_uplabs_news.jpg)

**Comment by FNPCMDs** [comment] 2020-06-28 06:15
> Hi all, just want to let you know that I have released a new version, and provide a way to disable the Center widget, please upgrade to v2.2.0 and give it a try.
> 
> I'm closing this issue, but if you have any further issues, feel free to reopen it.

Hi!, I'm trying to achieve same thing like @rivetingpeppermint. As you can see on the left picture, carousel is not centered, because it start at the left side. I tried to do that with the latest version but "disableCenter" is not working. Can you fix that ?

Greetings !

**Comment by DFelten** [comment] 2020-07-26 13:01
> The problem is I wanted something like this picture below (the one on the left), where the next carousel item peeks on the right. How can I achieve this?
> 
> ![screenshot](https://camo.githubusercontent.com/fe067cc6cceeed30cfe0ab214c0a572fc4800a5a/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f313735373131392f73637265656e73686f74732f353138353036332f706f73745f666f725f75706c6162735f6e6577732e6a7067)

Same issue here. Is it possible to align the slider to the left instead of center it?

**Comment by tzsword** [comment] 2020-09-20 14:01
[Left Aligned ViewPort in Page View ](https://github.com/flutter/flutter/issues/52014): https://github.com/flutter/flutter/issues/52014

**Comment by vukhacbiet** [comment] 2020-12-13 09:02
> > The problem is I wanted something like this picture below (the one on the left), where the next carousel item peeks on the right. How can I achieve this?
> > ![screenshot](https://camo.githubusercontent.com/fe067cc6cceeed30cfe0ab214c0a572fc4800a5a/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f313735373131392f73637265656e73686f74732f353138353036332f706f73745f666f725f75706c6162735f6e6577732e6a7067)
> 
> Same issue here. Is it possible to align the slider to the left instead of center it?

I need it too

**Comment by jacksonw765** [comment] 2020-12-13 15:27
@vukhacbiet I think your best bet is to use a listview with horizontal scroll instead.

**Comment by jacksonw765** [comment] 2020-12-13 15:28
> The problem is I wanted something like this picture below (the one on the left), where the next carousel item peeks on the right. How can I achieve this?
> 
> ![screenshot](https://camo.githubusercontent.com/d254088f8c28ca3fb02ff6d058ae1b87187df03928fbc83e2e0c32fe1e947b64/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f313735373131392f73637265656e73686f74732f353138353036332f706f73745f666f725f75706c6162735f6e6577732e6a7067)

I think your best bet is to use a listview with horizontal scroll instead.

**Comment by stormenergy91** [comment] 2023-01-12 14:44
> Hi all, just want to let you know that I have released a new version, and provide a way to disable the Center widget, please upgrade to v2.2.0 and give it a try.
> 
> I'm closing this issue, but if you have any further issues, feel free to reopen it.

@serenader2014  Where I can find the documentation about how disable the center option?
