### ISSUE TITLE
enlarge carousel item with width or ratio didn't work

### ISSUE THREAD

**Issue by masbenx** [serenader2014/flutter_carousel_slider#27] opened 2019-03-14 15:14 UTC
I want to set my carousel item width but it didn't work.

this is my code
```dart
return CarouselSlider(
    height: 480.0,
    items: [0,1,2].map((i) {
        return Builder(
        builder: (BuildContext context) {
            return Container(
            width: 500,
            margin: EdgeInsets.symmetric(horizontal: 11.0),
            decoration: BoxDecoration(
                color: Colors.amber,
                borderRadius: BorderRadius.circular(15.0),
                image: DecorationImage(image: AssetImage(imageString[i].toString()), fit: BoxFit.cover),
            ),
        );
    },
);
```

**Comment by red42** [comment] 2019-03-14 21:48
I believe the width of the items is defined by viewportFraction parameter. I am also looking for a way to have fixed-width items, but haven't figured out yet.

**Comment by red42** [comment] 2019-03-15 13:38
I created PR that enables setting the width of each item: #28 

This adds an itemWidth parameter that set the width of the items. If it's not set, the item takes the entire width defined by viewportFraction.

**Comment by joelbrostrom** [comment] 2019-03-18 16:38
I'm not sure what you want to do, but using the following code (your code with a few tweaks to make it work with the example project) lets me set the width to any value.
However, 500 is larger than most mobile screens.
Have you tried with a lower value?

```
final CarouselSlider testCarousel = CarouselSlider(
  viewportFraction: 1.0,
  items: imgList.map<Widget>(
    (url) {
      return Container(
        width: 200,
        margin: EdgeInsets.symmetric(horizontal: 0.0),
        decoration: BoxDecoration(
          color: Colors.amber,
          borderRadius: BorderRadius.circular(15.0),
          image: DecorationImage(image: NetworkImage(url), fit: BoxFit.cover),
        ),
      );
    },
  ).toList(),
);
```

This is the result:
width 200:
![Screenshot 2019-03-18 at 17 27 39](https://user-images.githubusercontent.com/26721535/54546615-5588be80-49a4-11e9-93eb-733428510276.png)

width 300: 
![Screenshot 2019-03-18 at 17 28 25](https://user-images.githubusercontent.com/26721535/54546649-6a655200-49a4-11e9-8717-755ce8d5b30c.png)

Width 500:
![Screenshot 2019-03-18 at 17 30 42](https://user-images.githubusercontent.com/26721535/54546673-78b36e00-49a4-11e9-9ec6-7877e4b16424.png)

Widh 900:
![Screenshot 2019-03-18 at 17 30 42](https://user-images.githubusercontent.com/26721535/54546762-a8fb0c80-49a4-11e9-8ee5-e491a6c5b900.png)

**Comment by serenader2014** [comment] 2019-03-19 13:45
I'm closing this issue, because it seems that the problem is solved. Feel free to reopen it if you still have some problems.

**Closed by serenader2014** 2019-03-19 13:45 UTC
