### ISSUE TITLE
Not working on Flutter Web when hosted on Firebase hosting

### ISSUE THREAD

**Issue by Tarlochan5268** [serenader2014/flutter_carousel_slider#268] opened 2021-04-18 14:49 UTC
Hi i wanted to let you know the package is not working when i hosted it on Firebase Hosting but its working in my local browser.. 

please help me solve the issue
<img width="964" alt="Screen Shot 2021-04-18 at 10 44 22 AM" src="https://user-images.githubusercontent.com/27397696/115149747-816b4800-a033-11eb-9d4c-ef6208845430.png">

**This work in my local machine** i mean above pic

<img width="946" alt="Screen Shot 2021-04-18 at 10 45 31 AM" src="https://user-images.githubusercontent.com/27397696/115149758-8b8d4680-a033-11eb-80f6-6f04556737fb.png">

This **doesnt work** when hosted on firebase hosting it doesnt even work anywhere else.

My Firebase Hosting website Link -> https://mywebportolio.web.app/#/
My Github Repo Link ->. https://github.com/Tarlochan5268/web_portfolio

**Comment by Tarlochan5268** [comment] 2021-04-20 02:09
Can someone Fot god sake Help me on this or should i use some other Package..

**Comment by prateekmedia** [comment] 2021-04-26 11:25
> Can someone Fot god sake Help me on this or should i use some other Package..

Use latest null safe version, cause your pubspec.lock has locked this package version to 3.0.0, you can update it by specifying latest nullsafe version in pubspec.

Also nullsafety is backward compatible so you can use null safe packages in non null safe code too.

Also I faced an issue with CarouselController more info here #267 , if you have it and you face same error then it might be due to null safety errors which @serenader2014 has not re solved yet.

**Comment by Tarlochan5268** [comment] 2021-04-26 19:37
> > Can someone Fot god sake Help me on this or should i use some other Package..
> 
> Use latest null safe version, cause your pubspec.lock has locked this package version to 3.0.0, you can update it by specifying latest nullsafe version in pubspec.
> 
> Also nullsafety is backward compatible so you can use null safe packages in non null safe code too.
> 
> Also I faced an issue with CarouselController more info here #267 , if you have it and you face same error then it might be due to null safety errors which @serenader2014 has not re solved yet.

looks like we facing the same issue .. so bad to wait for the fix to happen..

**Comment by prateekmedia** [comment] 2021-04-27 15:44
@Tarlochan5268 I fixed the null safe issue and soon will be creating a PR, you could test it locally to see if it works for you.

**Comment by prateekmedia** [comment] 2021-04-27 16:30
Can be fixed by #271

**Comment by cgs** [comment] 2021-05-25 21:08
I am also seeing this issue, hosted on Netlify. Don't think the host has anything to do with it. Images display ok in development, but when deploying they do not display. This is on @prateekmedia fork with updated null safety.

**Comment by cgs** [comment] 2021-05-25 21:34
Resolved the issue: be sure to use ```Image.asset``` instead of ```Image.network``` when specifying your slide images. I had copy/pasted the example code which uses Image.network. This is not a bug with the library and can be closed. /cc @Tarlochan5268 @prateekmedia

**Comment by Tarlochan5268** [comment] 2021-05-25 22:14
@cgs  Hi there Thanks for your information but U are wrong.. Go to my repository Copy the whole project host it on firebase website.. And check out yourself what works and not... Dude Only Thing that fixed it was Null safe version... Image.asset or Image. Network doesnt change much.. Image. Network also works... Now u  can close for being wrong..

**Comment by Tarlochan5268** [comment] 2021-05-25 22:19
Null safety + Network Image Resolved issue for me..

**Closed** 2021-05-25 22:19 UTC
