### ISSUE TITLE
Error: 'CarouselController' is imported from both...

### ISSUE THREAD

**Issue by nietsmmar** [serenader2014/flutter_carousel_slider#449] opened 2024-07-22 17:48 UTC
With newer flutter versions I get this error:

```
Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'package:carousel_slider/carousel_slider.dart';
```

**Comment by kishan-dhankecha** [comment] 2024-07-22 18:00
Duplicate of #442

**Closed** 2024-07-22 18:06 UTC
